---
- name: Install apt dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ apt_dependencies }}"

- name: Install role apt dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ role_apt_dependencies }}"
