---
# tasks file for ansible-tor-browser-crawler
- include: sync-crawler-dir.yml
  when: local_crawler_src_dir is defined
- include: clone-repository.yml
  when: local_crawler_src_dir is not defined
- include: install-apt-deps.yml
- include: install-python-deps.yml
- include: set-user-capture-abilities.yml
